repoLocation: "C:\\Users\\landsverka\\Documents\\Code\\code"

exec:
  commands:
    -
      name: 'postgres'
      command: "D:\\tools\\apache-maven-3.5.3\\bin\\mvn.cmd -f dbunit/pom.xml -B -e -Pit-config,postgresql verify"
    -
      name: 'mysql'
      command: "D:\\tools\\apache-maven-3.5.3\\bin\\mvn.cmd -f dbunit/pom.xml -B -e -Pit-config,mysql verify"
    -
      name: 'sqlserver'
      command: "D:\\tools\\apache-maven-3.5.3\\bin\\mvn.cmd -f dbunit/pom.xml -B -e -Pit-config,mssql41 verify"
    -
      name: 'oracle11g'
      command: "D:\\tools\\apache-maven-3.5.3\\bin\\mvn.cmd -f dbunit/pom.xml -B -e -Pit-config,oracle-ojdbc6 verify"

docker:
  host: tcp://localhost:2375
  tls-verify: false
  containers:
    -
      name: mysql
      image: dbunit/dbunit-it-mysql:1.0.0
      cmds:
        - /entrypoint.sh
        - mysqld
      internal-port: 3306
      external-port: 3306
    -
      name: postgres
      image: dbunit/dbunit-it-postgres:1.0.0
      cmds:
        - /docker-entrypoint.sh
        - postgres
      internal-port: 5432
      external-port: 5432
    -
      name: sqlserver
      image: dbunit/dbunit-it-sqlserver:1.0.1
      internal-port: 1433
      external-port: 1433
    -
      name: oracle11g
      image: dbunit/dbunit-it-oracle11g:1.0.1
      internal-port: 1521
      external-port: 1521
